server:
  port: 10500

spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.153.128:8848
        username: nacos
        password: nacos
    sentinel:
#      scg:
#        fallback:
#          mode: response
#          response-body: '{"code": 403, "mes": "限流了"}'
      transport:
        dashboard: 192.168.153.128:8080
      eager: true
      datasource:
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}-flow
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: gw-flow

    gateway:
      discovery:
        locator:
          # enabled default false
#          enabled: true
          lower-case-service-id: true
      routes:
        - id: cloud-account-service
          uri: lb://cloud-account-service
          predicates:
            - Path=/account/**
          filters:
            - SwaggerFilter= true
            - AuthenticationFilter= true
#            - StripPrefix=1
        - id: cloud-order-service
          uri: lb://cloud-order-service
          predicates:
            - Path=/order/**
          filters:
            - SwaggerFilter= true
            - RequestTimeFilter=true
#            - StripPrefix=1
        - id: cloud-product-service
          # LoadBalance
          uri: lb://cloud-product-service
          predicates:
            - Path=/product/**
          filters:
            # filter if request uri ends with '/v2/api-docs'
            - SwaggerFilter= true
            - RequestTimeFilter=false
##             StripPrefix=2 if /account/aaa/bbb then dispatch to lb://cloud-account-service/bbb
#            - StripPrefix=1